openapi: 3.0.0
info:
  version: 0.8.0
  title: 'More Cars API » Section 6: Performance'
  description: >-
    The More Cars API is divided into six sections. 
    <ul>
    <li> [Section 1 - Core](/apis-docs/more-cars.net/more-cars-api-section-1)<br>
    <li> [Section 2 - Multimedia](/apis-docs/more-cars.net/more-cars-api-section-2)<br>
    <li> [Section 3 - Presentation](/apis-docs/more-cars.net/more-cars-api-section-3)<br>
    <li> [Section 4 - Gaming](/apis-docs/more-cars.net/more-cars-api-section-4)<br>
    <li> [Section 5 - Motorsport](/apis-docs/more-cars.net/more-cars-api-section-5)<br>
    <li> [Section 6 - Performance](/apis-docs/more-cars.net/more-cars-api-section-6)<br>
    </ul>
    
    <p>
      This section covers the performance aspects, like top speed, fuel consumption, lap times, ratings and so on.
    </p>

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/more-cars.net/more-cars-api-section-6/0.8.0
  - description: Production API
    url: https://more-cars.net/api/v1
    
components:
  securitySchemes:
    Access_Token:
      type: apiKey
      name: access-token
      in: header

tags:
- name: "Lap Times"
  description: A `Lap Time` is the time a driver needed to complete one full lap (or stage) of a race track. Not limited to motorsport, can also be the lap times of car magazines or private drives.
  
- name: "Measurements"
  description: ...
  
- name: "Ratings"
  description: ...
  
paths:
  /lap-times:
    get:
      tags:
      - "Lap Times"
      summary: 
        "Get all Lap Times"
      description: >-
        Returns a collection of all `Lap Times` that are stored in the *More Cars* database.
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/parameters/pageParam'
        - $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/parameters/sortParam'
        - $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/parameters/sortDirectionParam'
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Lap_Time_COLLECTION'

    post:
      tags:
      - "Lap Times"
      summary: 
        "Create new Lap Time"
      description: >-
        Adds a new `Lap Time` to the More Cars database.
      security:
        - Access_Token: []
      requestBody:
        $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/requestBodies/Lap_Time'
      responses:
        '201':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Lap_Time_CREATED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '422':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/InvalidData'

  '/lap-times/{lap_time_id}':
    get:
      tags:
      - "Lap Times"
      summary: 
        "Get specific Lap Time"
      description: >-
        Returns a `Lap Time` specified by its ID.
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Lap_Time_ITEM'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'

    delete:
      tags:
      - "Lap Times"
      summary: 
        "Delete Lap Time"
      description: >-
        Deletes a `Lap Time`.
        <br><br>
        🔒 Operation requires elevated permissions.
      responses:
        '204':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Lap_Time_DELETED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'
      security:
        - Access_Token: []

    parameters:
      - name: lap_time_id
        in: path
        required: true
        schema:
          type: integer
        example: 390