openapi: 3.0.0
info:
  version: 0.8.0
  title: 'More Cars API » Section 7: Prices'
  description: >-
    The More Cars API is divided into seven sections. 
    <ul>
    <li> [Section 1 - Core](/apis-docs/more-cars.net/more-cars-api-section-1)<br>
    <li> [Section 2 - Multimedia](/apis-docs/more-cars.net/more-cars-api-section-2)<br>
    <li> [Section 3 - Presentation](/apis-docs/more-cars.net/more-cars-api-section-3)<br>
    <li> [Section 4 - Gaming](/apis-docs/more-cars.net/more-cars-api-section-4)<br>
    <li> [Section 5 - Motorsport](/apis-docs/more-cars.net/more-cars-api-section-5)<br>
    <li> [Section 6 - Performance](/apis-docs/more-cars.net/more-cars-api-section-6)<br>
    <li> [Section 7 - Prices](/apis-docs/more-cars.net/more-cars-api-section-7)<br>
    </ul>
    
    <p>
      This section covers the monetary aspects. How much did a car cost in which year and in which country?
    </p>

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/more-cars.net/more-cars-api-section-7/0.8.0
  - description: Production API
    url: https://more-cars.net/api/v1
    
components:
  securitySchemes:
    Access_Token:
      type: apiKey
      name: access-token
      in: header

tags:
- name: "Price"
  description: >-
    The `Price` is the amount of money that is asked for a car.
- name: "Currency"
  description: >-
    `Currency` is the money that is used in a country or a region of the world.
  
paths:
  /prices:
    get:
      tags:
      - "Price"
      summary: 
        "Get all Prices"
      description: >-
        Returns a collection of all `Prices` that are stored in the *More Cars* database.
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/parameters/pageParam'
        - $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/parameters/sortParam'
        - $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/parameters/sortDirectionParam'
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Price_COLLECTION'

    post:
      tags:
      - "Price"
      summary: 
        "Create new Price"
      description: >-
        Adds a new `Price` to the More Cars database.
      security:
        - Access_Token: []
      requestBody:
        $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/requestBodies/Price'
      responses:
        '201':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Price_CREATED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '422':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/InvalidData'

  '/prices/{price_id}':
    get:
      tags:
      - "Price"
      summary: 
        "Get specific Price"
      description: >-
        Returns a `Price` specified by its ID.
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Price_ITEM'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'

    delete:
      tags:
      - "Price"
      summary: 
        "Delete Price"
      description: >-
        Deletes a `Price`.
        <br><br>
        🔒 Operation requires elevated permissions.
      responses:
        '204':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Price_DELETED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'
      security:
        - Access_Token: []

    parameters:
      - name: price_id
        in: path
        required: true
        schema:
          type: integer
        example: 9999
        
  '/prices/{price_id}/car-model-variants':
    get:
      tags:
      - "Price"
      summary: 
        "Get connected Car Model Variant"
      description: >-
        Returns the `Car Model Variant` to which this price is attached.
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Car_Model_Variant_ITEM'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'

    parameters:
      - name: price_id
        in: path
        required: true
        schema:
          type: integer
        example: 9999

  '/prices/{price_id}/car-model-variants/{car_model_variant_id}':
    post:
      tags:
      - "Price"
      summary: 
        "Connect Car Model Variant"
      description: >-
        Connects an existing `Car Model Variant` to the specified `Price`.
      responses:
        '204':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Car_Model_Variant_CONNECTED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'
      security:
        - Access_Token: []

    delete:
      tags:
      - "Price"
      summary: 
        "Disconnect Car Model Variant"
      description: >-
        Disconnects a `Car Model Variant` from the specified `Price`.
        <br><br>
        🔒 Operation requires elevated permissions.
      responses:
        '204':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Car_Model_Variant_DISCONNECTED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'
      security:
        - Access_Token: []

    parameters:
      - name: price_id
        in: path
        required: true
        example: 9999
        schema:
          type: integer
      - name: car_model_variant_id
        in: path
        required: true
        schema:
          type: integer
        example: 9999
        
  '/prices/{price_id}/countries':
    get:
      tags:
      - "Price"
      summary: 
        "Get connected Country"
      description: >-
        Returns the `Country` in which this price is/was valid.
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Country_ITEM'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'

    parameters:
      - name: price_id
        in: path
        required: true
        schema:
          type: integer
        example: 9999

  '/prices/{price_id}/countries/{country_id}':
    post:
      tags:
      - "Price"
      summary: 
        "Connect Country"
      description: >-
        Connects an existing `Country` to the specified `Price`.
      responses:
        '204':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Country_CONNECTED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'
      security:
        - Access_Token: []

    delete:
      tags:
      - "Price"
      summary: 
        "Disconnect Country"
      description: >-
        Disconnects a `Country` from the specified `Price`.
        <br><br>
        🔒 Operation requires elevated permissions.
      responses:
        '204':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Country_DISCONNECTED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'
      security:
        - Access_Token: []

    parameters:
      - name: price_id
        in: path
        required: true
        example: 9999
        schema:
          type: integer
      - name: country_id
        in: path
        required: true
        schema:
          type: integer
        example: 9999

  /currencies:
    get:
      tags:
      - "Currency"
      summary: 
        "Get all Currencies"
      description: >-
        Returns a collection of all `Currencies` that are stored in the *More Cars* database.
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/parameters/pageParam'
        - $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/parameters/sortParam'
        - $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/parameters/sortDirectionParam'
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Currency_COLLECTION'

    post:
      tags:
      - "Currency"
      summary: 
        "Create new Currency"
      description: >-
        Adds a new `Currency` to the More Cars database.
      security:
        - Access_Token: []
      requestBody:
        $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/requestBodies/Currency'
      responses:
        '201':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Currency_CREATED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '422':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/InvalidData'

  '/currencies/{currency_id}':
    get:
      tags:
      - "Currency"
      summary: 
        "Get specific Currency"
      description: >-
        Returns a `Currency` specified by its ID.
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Currency_ITEM'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'

    delete:
      tags:
      - "Currency"
      summary: 
        "Delete Currency"
      description: >-
        Deletes a `Currency`.
        <br><br>
        🔒 Operation requires elevated permissions.
      responses:
        '204':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Currency_DELETED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'
      security:
        - Access_Token: []

    parameters:
      - name: currency_id
        in: path
        required: true
        schema:
          type: integer
        example: 9999
        
  '/currencies/{currency_id}/countries':
    get:
      tags:
      - "Currency"
      summary: 
        "Get connected Countries"
      description: >-
        Returns the `Countries` in which this is the official currency.
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Country_COLLECTION'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'

    parameters:
      - name: currency_id
        in: path
        required: true
        schema:
          type: integer
        example: 9999

  '/currencies/{currency_id}/countries/{country_id}':
    post:
      tags:
      - "Currency"
      summary: 
        "Connect Country"
      description: >-
        Connects an existing `Country` to the specified `Currency`.
      responses:
        '204':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Country_CONNECTED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'
      security:
        - Access_Token: []

    delete:
      tags:
      - "Currency"
      summary: 
        "Disconnect Country"
      description: >-
        Disconnects a `Country` from the specified `Currency`.
        <br><br>
        🔒 Operation requires elevated permissions.
      responses:
        '204':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/Country_DISCONNECTED'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotAuthorized'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/more-cars.net/more-cars-api-section-0/0.8.0#/components/responses/NotFound'
      security:
        - Access_Token: []

    parameters:
      - name: currency_id
        in: path
        required: true
        example: 9999
        schema:
          type: integer
      - name: country_id
        in: path
        required: true
        schema:
          type: integer
        example: 130