openapi: 3.0.0
info:
  version: 0.8.0
  title: 'More Cars API » Section 6: Performance'
  description: >-
    The More Cars API is divided into six sections. 
    <ul>
    <li> [Section 1 - Core](/apis-docs/more-cars.net/more-cars-api-section-1)<br>
    <li> [Section 2 - Multimedia](/apis-docs/more-cars.net/more-cars-api-section-2)<br>
    <li> [Section 3 - Presentation](/apis-docs/more-cars.net/more-cars-api-section-3)<br>
    <li> [Section 4 - Gaming](/apis-docs/more-cars.net/more-cars-api-section-4)<br>
    <li> [Section 5 - Motorsport](/apis-docs/more-cars.net/more-cars-api-section-5)<br>
    <li> [Section 6 - Performance](/apis-docs/more-cars.net/more-cars-api-section-6)<br>
    </ul>
    
    <p>
      This section covers the performance aspects, like top speed, fuel consumption, lap times, ratings, ...
    </p>
paths: {}
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/more-cars.net/more-cars-api-section-6/0.8.0
  - description: Production API
    url: https://more-cars.net/api/v1
    
components:
  securitySchemes:
    Access_Token:
      type: apiKey
      name: access-token
      in: header

tags:
- name: "Lap Times"
  description: ...
  
- name: "Measurements"
  description: ...
  
- name: "Ratings"
  description: ...